/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BusinessRouteImport } from './routes/business'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BusinessIndexRouteImport } from './routes/business.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as BusinessStoreRouteImport } from './routes/business.store'
import { Route as BusinessProductsRouteImport } from './routes/business.products'
import { Route as BusinessPlaceholderRouteImport } from './routes/business.placeholder'
import { Route as BusinessOrdersRouteImport } from './routes/business.orders'
import { Route as BusinessCreateRouteImport } from './routes/business.create'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTicketsRouteImport } from './routes/admin.tickets'
import { Route as AdminScansRouteImport } from './routes/admin.scans'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminPricingRouteImport } from './routes/admin.pricing'
import { Route as AdminLogsRouteImport } from './routes/admin.logs'
import { Route as AdminAdminsRouteImport } from './routes/admin.admins'
import { Route as AuthenticatedScanNewRouteImport } from './routes/_authenticated.scan.new'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessRoute = BusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessIndexRoute = BusinessIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BusinessRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const BusinessStoreRoute = BusinessStoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => BusinessRoute,
} as any)
const BusinessProductsRoute = BusinessProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => BusinessRoute,
} as any)
const BusinessPlaceholderRoute = BusinessPlaceholderRouteImport.update({
  id: '/placeholder',
  path: '/placeholder',
  getParentRoute: () => BusinessRoute,
} as any)
const BusinessOrdersRoute = BusinessOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => BusinessRoute,
} as any)
const BusinessCreateRoute = BusinessCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => BusinessRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTicketsRoute = AdminTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AdminRoute,
} as any)
const AdminScansRoute = AdminScansRouteImport.update({
  id: '/scans',
  path: '/scans',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPricingRoute = AdminPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminsRoute = AdminAdminsRouteImport.update({
  id: '/admins',
  path: '/admins',
  getParentRoute: () => AdminRoute,
} as any)
const AuthenticatedScanNewRoute = AuthenticatedScanNewRouteImport.update({
  id: '/scan/new',
  path: '/scan/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/admin': typeof AdminRouteWithChildren
  '/business': typeof BusinessRouteWithChildren
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/discover': typeof DiscoverRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/scans': typeof AdminScansRoute
  '/admin/tickets': typeof AdminTicketsRoute
  '/admin/users': typeof AdminUsersRoute
  '/business/create': typeof BusinessCreateRoute
  '/business/orders': typeof BusinessOrdersRoute
  '/business/placeholder': typeof BusinessPlaceholderRoute
  '/business/products': typeof BusinessProductsRoute
  '/business/store': typeof BusinessStoreRoute
  '/admin/': typeof AdminIndexRoute
  '/business/': typeof BusinessIndexRoute
  '/scan/new': typeof AuthenticatedScanNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/discover': typeof DiscoverRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/scans': typeof AdminScansRoute
  '/admin/tickets': typeof AdminTicketsRoute
  '/admin/users': typeof AdminUsersRoute
  '/business/create': typeof BusinessCreateRoute
  '/business/orders': typeof BusinessOrdersRoute
  '/business/placeholder': typeof BusinessPlaceholderRoute
  '/business/products': typeof BusinessProductsRoute
  '/business/store': typeof BusinessStoreRoute
  '/admin': typeof AdminIndexRoute
  '/business': typeof BusinessIndexRoute
  '/scan/new': typeof AuthenticatedScanNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/business': typeof BusinessRouteWithChildren
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/discover': typeof DiscoverRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/scans': typeof AdminScansRoute
  '/admin/tickets': typeof AdminTicketsRoute
  '/admin/users': typeof AdminUsersRoute
  '/business/create': typeof BusinessCreateRoute
  '/business/orders': typeof BusinessOrdersRoute
  '/business/placeholder': typeof BusinessPlaceholderRoute
  '/business/products': typeof BusinessProductsRoute
  '/business/store': typeof BusinessStoreRoute
  '/admin/': typeof AdminIndexRoute
  '/business/': typeof BusinessIndexRoute
  '/_authenticated/scan/new': typeof AuthenticatedScanNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/admin'
    | '/business'
    | '/contact'
    | '/dashboard'
    | '/discover'
    | '/login'
    | '/pricing'
    | '/profile'
    | '/reset-password'
    | '/signup'
    | '/admin/admins'
    | '/admin/logs'
    | '/admin/pricing'
    | '/admin/reports'
    | '/admin/scans'
    | '/admin/tickets'
    | '/admin/users'
    | '/business/create'
    | '/business/orders'
    | '/business/placeholder'
    | '/business/products'
    | '/business/store'
    | '/admin/'
    | '/business/'
    | '/scan/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/contact'
    | '/dashboard'
    | '/discover'
    | '/login'
    | '/pricing'
    | '/profile'
    | '/reset-password'
    | '/signup'
    | '/admin/admins'
    | '/admin/logs'
    | '/admin/pricing'
    | '/admin/reports'
    | '/admin/scans'
    | '/admin/tickets'
    | '/admin/users'
    | '/business/create'
    | '/business/orders'
    | '/business/placeholder'
    | '/business/products'
    | '/business/store'
    | '/admin'
    | '/business'
    | '/scan/new'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/_authenticated'
    | '/admin'
    | '/business'
    | '/contact'
    | '/dashboard'
    | '/discover'
    | '/login'
    | '/pricing'
    | '/profile'
    | '/reset-password'
    | '/signup'
    | '/admin/admins'
    | '/admin/logs'
    | '/admin/pricing'
    | '/admin/reports'
    | '/admin/scans'
    | '/admin/tickets'
    | '/admin/users'
    | '/business/create'
    | '/business/orders'
    | '/business/placeholder'
    | '/business/products'
    | '/business/store'
    | '/admin/'
    | '/business/'
    | '/_authenticated/scan/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  BusinessRoute: typeof BusinessRouteWithChildren
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  DiscoverRoute: typeof DiscoverRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business': {
      id: '/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof BusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/': {
      id: '/business/'
      path: '/'
      fullPath: '/business/'
      preLoaderRoute: typeof BusinessIndexRouteImport
      parentRoute: typeof BusinessRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/business/store': {
      id: '/business/store'
      path: '/store'
      fullPath: '/business/store'
      preLoaderRoute: typeof BusinessStoreRouteImport
      parentRoute: typeof BusinessRoute
    }
    '/business/products': {
      id: '/business/products'
      path: '/products'
      fullPath: '/business/products'
      preLoaderRoute: typeof BusinessProductsRouteImport
      parentRoute: typeof BusinessRoute
    }
    '/business/placeholder': {
      id: '/business/placeholder'
      path: '/placeholder'
      fullPath: '/business/placeholder'
      preLoaderRoute: typeof BusinessPlaceholderRouteImport
      parentRoute: typeof BusinessRoute
    }
    '/business/orders': {
      id: '/business/orders'
      path: '/orders'
      fullPath: '/business/orders'
      preLoaderRoute: typeof BusinessOrdersRouteImport
      parentRoute: typeof BusinessRoute
    }
    '/business/create': {
      id: '/business/create'
      path: '/create'
      fullPath: '/business/create'
      preLoaderRoute: typeof BusinessCreateRouteImport
      parentRoute: typeof BusinessRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tickets': {
      id: '/admin/tickets'
      path: '/tickets'
      fullPath: '/admin/tickets'
      preLoaderRoute: typeof AdminTicketsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/scans': {
      id: '/admin/scans'
      path: '/scans'
      fullPath: '/admin/scans'
      preLoaderRoute: typeof AdminScansRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pricing': {
      id: '/admin/pricing'
      path: '/pricing'
      fullPath: '/admin/pricing'
      preLoaderRoute: typeof AdminPricingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/admins': {
      id: '/admin/admins'
      path: '/admins'
      fullPath: '/admin/admins'
      preLoaderRoute: typeof AdminAdminsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_authenticated/scan/new': {
      id: '/_authenticated/scan/new'
      path: '/scan/new'
      fullPath: '/scan/new'
      preLoaderRoute: typeof AuthenticatedScanNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedScanNewRoute: typeof AuthenticatedScanNewRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedScanNewRoute: AuthenticatedScanNewRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface AdminRouteChildren {
  AdminAdminsRoute: typeof AdminAdminsRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminPricingRoute: typeof AdminPricingRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminScansRoute: typeof AdminScansRoute
  AdminTicketsRoute: typeof AdminTicketsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminsRoute: AdminAdminsRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminPricingRoute: AdminPricingRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminScansRoute: AdminScansRoute,
  AdminTicketsRoute: AdminTicketsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BusinessRouteChildren {
  BusinessCreateRoute: typeof BusinessCreateRoute
  BusinessOrdersRoute: typeof BusinessOrdersRoute
  BusinessPlaceholderRoute: typeof BusinessPlaceholderRoute
  BusinessProductsRoute: typeof BusinessProductsRoute
  BusinessStoreRoute: typeof BusinessStoreRoute
  BusinessIndexRoute: typeof BusinessIndexRoute
}

const BusinessRouteChildren: BusinessRouteChildren = {
  BusinessCreateRoute: BusinessCreateRoute,
  BusinessOrdersRoute: BusinessOrdersRoute,
  BusinessPlaceholderRoute: BusinessPlaceholderRoute,
  BusinessProductsRoute: BusinessProductsRoute,
  BusinessStoreRoute: BusinessStoreRoute,
  BusinessIndexRoute: BusinessIndexRoute,
}

const BusinessRouteWithChildren = BusinessRoute._addFileChildren(
  BusinessRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  BusinessRoute: BusinessRouteWithChildren,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  DiscoverRoute: DiscoverRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
